sudo: required
services:
  - docker
env:
  - SITE_URL=http://geb-herrenberg.de
  - SITE_URL=http://www.eltern-sgh.de/
  - SITE_URL=http://freunde-sgh.de/
script:
- "docker run stupchiy/checklink --recursive --broken -e $SITE_URL"
